from __future__ import annotations

from app.noodle.schemas import NoodlePipelineIntent, NoodleReferenceSpec


def _reference_spec(
    *,
    spec_id: str,
    name: str,
    summary: str,
    tags: list[str],
    intent_name: str,
    business_goal: str,
    deployment_scope: str,
    latency_slo: str,
    requires_ml_features: bool,
    requires_realtime_serving: bool,
    contains_sensitive_data: bool,
    target_consumers: list[str],
    sources: list[dict[str, str]],
) -> NoodleReferenceSpec:
    return NoodleReferenceSpec(
        id=spec_id,
        name=name,
        summary=summary,
        tags=tags,
        sample_intent=NoodlePipelineIntent(
            name=intent_name,
            business_goal=business_goal,
            deployment_scope=deployment_scope,  # type: ignore[arg-type]
            latency_slo=latency_slo,  # type: ignore[arg-type]
            requires_ml_features=requires_ml_features,
            requires_realtime_serving=requires_realtime_serving,
            contains_sensitive_data=contains_sensitive_data,
            target_consumers=target_consumers,
            sources=sources,
        ),
    )


REFERENCE_SPECS: list[NoodleReferenceSpec] = [
    _reference_spec(
        spec_id="hybrid-orders-analytics",
        name="Hybrid Orders To Lakehouse",
        summary="Unifies on-prem ERP orders with cloud clickstream and publishes a governed gold dataset.",
        tags=["hybrid", "lakehouse", "analytics"],
        intent_name="hybrid-orders-analytics",
        business_goal="Create a trusted source of truth for order intelligence across ERP and digital channels.",
        deployment_scope="hybrid_multi_cloud",
        latency_slo="minutes",
        requires_ml_features=True,
        requires_realtime_serving=True,
        contains_sensitive_data=True,
        target_consumers=["bi", "operations_api", "demand_forecasting_model"],
        sources=[
            {
                "name": "erp_orders",
                "kind": "database",
                "environment": "on_prem",
                "format_hint": "oracle relational",
                "change_pattern": "cdc",
            },
            {
                "name": "web_clickstream",
                "kind": "stream",
                "environment": "aws",
                "format_hint": "json events",
                "change_pattern": "event",
            },
            {
                "name": "warehouse_scanners",
                "kind": "iot",
                "environment": "edge",
                "format_hint": "protobuf telemetry",
                "change_pattern": "event",
            },
        ],
    ),
    _reference_spec(
        spec_id="multicloud-customer-360",
        name="Multi-Cloud Customer 360",
        summary="Creates a cross-cloud customer profile by merging SaaS, CRM, support, and product telemetry.",
        tags=["multi_cloud", "customer_360", "serving"],
        intent_name="customer-360",
        business_goal="Build a single customer profile that powers BI, support routing, and churn scoring.",
        deployment_scope="multi_cloud",
        latency_slo="hours",
        requires_ml_features=True,
        requires_realtime_serving=False,
        contains_sensitive_data=True,
        target_consumers=["bi", "support_console", "retention_model"],
        sources=[
            {
                "name": "salesforce_accounts",
                "kind": "saas",
                "environment": "saas",
                "format_hint": "salesforce objects",
                "change_pattern": "snapshot",
            },
            {
                "name": "product_usage",
                "kind": "stream",
                "environment": "gcp",
                "format_hint": "avro events",
                "change_pattern": "event",
            },
        ],
    ),
    _reference_spec(
        spec_id="github-engineering-intelligence",
        name="GitHub Engineering Intelligence",
        summary="Collects GitHub repository events, pull requests, and deployment metadata into an engineering analytics pipeline.",
        tags=["github", "engineering", "analytics"],
        intent_name="github-engineering-intelligence",
        business_goal="Create an engineering intelligence pipeline that tracks repository activity, pull request flow, and deployment lead time.",
        deployment_scope="multi_cloud",
        latency_slo="minutes",
        requires_ml_features=False,
        requires_realtime_serving=False,
        contains_sensitive_data=False,
        target_consumers=["bi", "engineering_ops", "delivery_insights_api"],
        sources=[
            {
                "name": "github_events",
                "kind": "github",
                "environment": "saas",
                "format_hint": "github webhooks and graphql objects",
                "change_pattern": "event",
            },
            {
                "name": "ci_deployments",
                "kind": "api",
                "environment": "aws",
                "format_hint": "json deployment events",
                "change_pattern": "append",
            },
        ],
    ),
    _reference_spec(
        spec_id="finance-close-reconciliation",
        name="Finance Close Reconciliation",
        summary="Reconciles ledger extracts, payment settlement files, and ERP balances into a governed finance close dataset.",
        tags=["finance", "file", "compliance", "batch"],
        intent_name="finance-close-reconciliation",
        business_goal="Standardize finance close inputs and publish auditable reconciliations for controllers and BI.",
        deployment_scope="hybrid",
        latency_slo="daily",
        requires_ml_features=False,
        requires_realtime_serving=False,
        contains_sensitive_data=True,
        target_consumers=["finance_bi", "controller_console", "audit_ops"],
        sources=[
            {
                "name": "payment_settlement_files",
                "kind": "file",
                "environment": "saas",
                "format_hint": "csv settlement extracts",
                "change_pattern": "snapshot",
            },
            {
                "name": "erp_ledger",
                "kind": "database",
                "environment": "on_prem",
                "format_hint": "postgres relational",
                "change_pattern": "snapshot",
            },
        ],
    ),
    _reference_spec(
        spec_id="partner-api-operations-sync",
        name="Partner API Operations Sync",
        summary="Combines partner APIs and SaaS support signals for near-real-time operational sync and service oversight.",
        tags=["api", "operations", "saas", "hybrid"],
        intent_name="partner-api-operations-sync",
        business_goal="Continuously sync partner order status, ticket data, and SLA exceptions into a shared operations view.",
        deployment_scope="hybrid",
        latency_slo="minutes",
        requires_ml_features=False,
        requires_realtime_serving=True,
        contains_sensitive_data=False,
        target_consumers=["partner_ops", "support_api", "sla_dashboard"],
        sources=[
            {
                "name": "partner_order_api",
                "kind": "api",
                "environment": "aws",
                "format_hint": "rest json",
                "change_pattern": "append",
            },
            {
                "name": "zendesk_cases",
                "kind": "saas",
                "environment": "saas",
                "format_hint": "zendesk tickets",
                "change_pattern": "snapshot",
            },
        ],
    ),
    _reference_spec(
        spec_id="edge-predictive-maintenance",
        name="Edge Predictive Maintenance",
        summary="Streams equipment telemetry from the edge into low-latency maintenance alerts and reusable ML features.",
        tags=["edge", "iot", "predictive_maintenance", "realtime"],
        intent_name="edge-predictive-maintenance",
        business_goal="Detect equipment degradation in seconds and publish both live alerts and maintenance model features.",
        deployment_scope="edge",
        latency_slo="seconds",
        requires_ml_features=True,
        requires_realtime_serving=True,
        contains_sensitive_data=False,
        target_consumers=["maintenance_ops", "alerting_api", "failure_prediction_model"],
        sources=[
            {
                "name": "machine_telemetry",
                "kind": "iot",
                "environment": "edge",
                "format_hint": "protobuf telemetry",
                "change_pattern": "event",
            }
        ],
    ),
    _reference_spec(
        spec_id="regulated-claims-lakehouse",
        name="Regulated Claims Lakehouse",
        summary="Consolidates claims files, policy records, and third-party adjudication feeds under strict privacy and residency controls.",
        tags=["insurance", "file", "database", "regulated"],
        intent_name="regulated-claims-lakehouse",
        business_goal="Create a governed claims lakehouse for adjudication analytics, audit, and downstream actuarial consumption.",
        deployment_scope="hybrid_multi_cloud",
        latency_slo="hours",
        requires_ml_features=True,
        requires_realtime_serving=False,
        contains_sensitive_data=True,
        target_consumers=["claims_bi", "actuarial_model", "audit_console"],
        sources=[
            {
                "name": "claims_dropzone",
                "kind": "file",
                "environment": "azure",
                "format_hint": "parquet claims extracts",
                "change_pattern": "append",
            },
            {
                "name": "policy_admin",
                "kind": "database",
                "environment": "on_prem",
                "format_hint": "sqlserver relational",
                "change_pattern": "cdc",
            },
            {
                "name": "adjudication_partner_api",
                "kind": "api",
                "environment": "gcp",
                "format_hint": "json adjudication events",
                "change_pattern": "append",
            },
        ],
    ),
    _reference_spec(
        spec_id="lakehouse-backfill-archive",
        name="Lakehouse Backfill Archive",
        summary="Loads historical archive files into bronze and silver zones for long-horizon analytical backfill.",
        tags=["archive", "backfill", "file", "batch"],
        intent_name="lakehouse-backfill-archive",
        business_goal="Backfill historical datasets from archive exports without adding low-latency serving requirements.",
        deployment_scope="multi_cloud",
        latency_slo="daily",
        requires_ml_features=False,
        requires_realtime_serving=False,
        contains_sensitive_data=False,
        target_consumers=["bi", "historical_analytics"],
        sources=[
            {
                "name": "archive_exports",
                "kind": "file",
                "environment": "aws",
                "format_hint": "csv and parquet archives",
                "change_pattern": "snapshot",
            }
        ],
    ),
    _reference_spec(
        spec_id="realtime-fraud-decisioning",
        name="Realtime Fraud Decisioning",
        summary="Correlates transaction streams and payment APIs for sub-second fraud detection and decision-serving.",
        tags=["fraud", "stream", "api", "realtime"],
        intent_name="realtime-fraud-decisioning",
        business_goal="Score risky transactions in seconds and publish governed decision features for fraud operations.",
        deployment_scope="multi_cloud",
        latency_slo="seconds",
        requires_ml_features=True,
        requires_realtime_serving=True,
        contains_sensitive_data=True,
        target_consumers=["fraud_ops", "decision_api", "fraud_model"],
        sources=[
            {
                "name": "card_authorizations",
                "kind": "stream",
                "environment": "aws",
                "format_hint": "avro card events",
                "change_pattern": "event",
            },
            {
                "name": "payment_gateway_api",
                "kind": "api",
                "environment": "saas",
                "format_hint": "rest payment api",
                "change_pattern": "append",
            },
        ],
    ),
    _reference_spec(
        spec_id="crm-support-unification",
        name="CRM Support Unification",
        summary="Blends CRM, support, and knowledge base SaaS data into a unified service performance model.",
        tags=["saas", "crm", "support", "customer_ops"],
        intent_name="crm-support-unification",
        business_goal="Merge CRM and support signals into a common model for service leadership, BI, and automation.",
        deployment_scope="multi_cloud",
        latency_slo="hours",
        requires_ml_features=False,
        requires_realtime_serving=False,
        contains_sensitive_data=True,
        target_consumers=["support_bi", "service_leadership", "automation_ops"],
        sources=[
            {
                "name": "salesforce_accounts",
                "kind": "saas",
                "environment": "saas",
                "format_hint": "salesforce crm",
                "change_pattern": "snapshot",
            },
            {
                "name": "knowledge_base_api",
                "kind": "api",
                "environment": "saas",
                "format_hint": "json articles and events",
                "change_pattern": "append",
            },
        ],
    ),
]
